<!DOCTYPE html>
<html lang="en">

<?php

include("config.php");

// Connect to the database
// $dbconnect = mysqli_connect(DB_HOST, DB_USERNAME, DB_PASSWORD, DB_NAME);

if (mysqli_connect_errno())
{
	echo "Connection failed:".mysqli_connect_error();
	exit;
}

?>


	<!-- This code is generated by Chat Gpt -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Nicke-Lee v.d Berg">
    <meta name="description" content="Explore the world of school sports, including events, training tips, athlete profiles, and the benefits of sports in education.">
    <meta name="keywords" content="school sports, athletics, student athletes, sports events, training, physical education, teamwork, sports benefits, youth sports, sports programs">
	
    <title>School Sports</title>
	
	<!-- Style sheets area -->
    <link rel="stylesheet" href="sports_style.css">
	
	<!-- Icon for tabs / bookmarks -->
    <link rel="icon" type="image/x-icon" href="images/favicon.ico">
	
	<!-- Fonts links -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Agbalumo&family=Open+Sans&display=swap" rel="stylesheet">

    <!-- Font Awesome Link (for search icon) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" >
	
</head>

            

        
